(* Bounds-checked vector indexing via the Inductive command.

   [nat] and [t] are declared with [Inductive] (indexed Boehm-Berarducci), so
   the fold [t_rec] is generated and computes.  [nth] indexes a [t A n] by
   a [Fin n], so out-of-bounds access is a type error.

   The tension made concrete: [nth] needs one-step INVERSION on a [Fin] (is the
   index zero or a successor?), which is not the fold [t_rec]/[Fin_rec] and is
   not derivable from the impredicative encoding.  So [Fin] and its inversion
   principles [fin0]/[fin_case] are kept axiomatic; [nat] and [t] use
   [Inductive]. *)


Inductive nat : Set := | O : nat | S : nat -> nat.

Inductive t (A : Set) : nat -> Set :=
  | nil : t A O
  | cons : forall (n : nat), A -> t A n -> t A (S n).

(* Bounded indices.  [Fin] and its recursor are generated by [Inductive]; only
   the one-step inversion principles [fin0] (empty) and [fin_case] (successor),
   which a fold cannot provide, stay axiomatic. *)
Inductive Fin : nat -> Set :=
  | F1 : forall (n : nat), Fin (S n)
  | FS : forall (n : nat), Fin n -> Fin (S n).

Axiom fin0 : forall (C : Set), Fin O -> C.
Axiom fin_case :
  forall (n : nat) (C : Set), C -> (Fin n -> C) -> Fin (S n) -> C.


(* Total, bounds-checked lookup, by recursion on the vector (generated
   [t_rec]) at the motive [X m = Fin m -> A]. *)

Definition nth (A : Set) (n : nat) (xs : t A n) (i : Fin n) : A :=
  t_rec A (fun (m : nat) => Fin m -> A)
    (fun (i0 : Fin O) => fin0 A i0)
    (fun (m : nat) (a : A) (rest : Fin m -> A) (j : Fin (S m)) =>
     fin_case m A a rest j)
    n xs i.

Check nth.
Extract nth.


(* head of a provably non-empty vector. *)

Extract fun (A : Set) (n : nat) (xs : t A (S n)) =>
  nth A (S n) xs (F1 n).


(* second element of a vector of length at least two. *)

Extract fun (A : Set) (n : nat) (xs : t A (S (S n))) =>
  nth A (S (S n)) xs (FS (S n) (F1 n)).


(* weakening an index into a longer vector. *)

Extract fun (n : nat) (i : Fin n) => FS n i.


(* The boundary.  The family [Fin], as a function from a nat to a type, is a
   value in type position with no Fomega image -- extraction emits [Dyn] and an
   internal blame. *)

Extract fun (n : nat) => Fin n.
