(* Session-typed / typestate protocols via the Inductive command.

   [Chan] is declared with [Inductive] as a family indexed by protocol state,
   so its constructor and the fold [Chan_rec] are generated by the indexed
   Boehm-Berarducci encoding.  The operations are indexed by state, so the
   protocol ORDERING is enforced by the types: [recv] needs a [Sent] channel,
   [close] a [Done] one.  Extraction erases the state index. *)


Inductive St : Set := | Ready : St | Sent : St | Done : St.

Inductive Msg : Set := | greeting : Msg.

Inductive Chan : St -> Set := | mkchan : forall (s : St), Msg -> Chan s.

(* Chan_rec : forall (X : St -> Set), (forall s, Msg -> X s) -> forall s, Chan s -> X s *)

Definition open : Chan Ready :=
  mkchan Ready greeting.

Definition send (m : Msg) (c : Chan Ready) : Chan Sent :=
  mkchan Sent m.

Definition recv (c : Chan Sent) : Chan Done :=          (* the echo "network" *)
  mkchan Done
    (Chan_rec (fun (_ : St) => Msg) (fun (s : St) (m : Msg) => m) Sent c).

Definition close (c : Chan Done) : Msg :=               (* yields the reply *)
  Chan_rec (fun (_ : St) => Msg) (fun (s : St) (m : Msg) => m) Done c.


(* the one legal run of the protocol: open, send, recv, close. *)

Check fun (req : Msg) => close (recv (send req open)).

Extract fun (req : Msg) => close (recv (send req open)).


(* a client abstract over its starting channel. *)

Extract fun (req : Msg) (c : Chan Ready) => close (recv (send req c)).


(* just the send step, exposing the state transition Ready -> Sent. *)

Extract fun (req : Msg) (c : Chan Ready) => send req c.
